services:
  postgres:
    image: postgres:16-alpine
    container_name: minipay-postgres
    environment:
      POSTGRES_DB: minipay_db
      POSTGRES_USER: minipay_user
      POSTGRES_PASSWORD: minipay_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U minipay_user -d minipay_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: minipay-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@minipay.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
